[package]
name = "rl_custom_complete"
version = "0.1.0"
authors = ["林千里 <lincheney@gmail.com>"]

[dependencies]
libc = "0.2.66"
once_cell = "1.17.1"

[lib]
name = "rl_custom_complete"
crate-type = ["cdylib"]
